<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SurvivalcraftGenius.ToolBench</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SurvivalcraftGenius\SurvivalcraftGenius.csproj" />
    <Reference Include="Survivalcraft">
      <HintPath>$(SurvivalcraftDir)Survivalcraft.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Engine">
      <HintPath>$(SurvivalcraftDir)Engine.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="EntitySystem">
      <HintPath>$(SurvivalcraftDir)EntitySystem.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(SurvivalcraftDir)Newtonsoft.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
